### ISSUE TITLE
[feature] Compatibility with DataFrames v1

### ISSUE THREAD

**Issue by hannesbecher** [pdimens/PopGen.jl#71]
Hi there,
Great to see this project! Thanks for implementing this!

**Is your feature request related to a problem and which?**
At the moment, PopGen does not work with (fast and snazzy) DataFrames v1:
```
(popgen) pkg> add PopGen DataFrames@1
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DataFrames [a93c6f00]:
 DataFrames [a93c6f00] log:
 ├─possible versions are: 0.11.7-1.1.0 or uninstalled
 ├─restricted to versions 1 by an explicit requirement, leaving only versions 1.0.0-1.1.0
 └─restricted by compatibility requirements with PopGen [af524d12] to versions: 0.11.7-0.22.7 — no versions left
   └─PopGen [af524d12] log:
     ├─possible versions are: 0.0.3-0.6.3 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.0.3-0.6.3
```
**Describe the solution/feature you'd like (with examples)**
Would it be possible (within reasonable effort) to make them work together?

Many thanks!
Hannes

**Comment by pdimens** [comment]
I just updated the compat in the `dev` branch this morning
 Try installing with 
`]add PopGen#dev` and let me know if it still fails. If it works, I'll tag a new release. If not, I'll dig into what's going wrong. Thanks for the heads up!

**Comment by pdimens** [comment]
Adding the dev branch seems to work on my machine. I'll tag the next release. Let me know if that doesn't work. #72

**Comment by hannesbecher** [comment]
Work for me, too.
Thanks!

**Comment by pdimens** [comment]
Thanks for spotting this!
